#!/bin/bash

MODEL_CFG=$1
MODE=zeroshot
CKPT=$2
OUTPUT_DIR=/checkpoints/sunxm/output/evaluations/

# 1
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=caltech101  CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 2
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=cifar10  CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 3
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=cifar100  CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 4
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=country211  CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 5
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=dtd  CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 6
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=eurosat-clip  CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 7
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=fer2013 CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 8
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=fgvc-aircraft-2013b CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 9
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=flower102 CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 10
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=food101 CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 11
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=gtsrb CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 12
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=hateful-memes CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 13
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=imagenet-1k CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 14
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=kitti-distance CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 15
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=mnist CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 16
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=oxford-iiit-pets CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 17
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=patchcamelyon CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 18
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=rendered-sst2 CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 19
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=resisc45-clip CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 20
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=stanfordcar CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh
# 21
CUDA_VISIBLE_DEVICES=0 MODEL_CFG=$MODEL_CFG MODE=$MODE DATASET=voc2007classification CKPT=$CKPT  OUTPUT_DIR=$OUTPUT_DIR bash run_multi.sh

